App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'


urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike'),





]

App_RegLog/urls.py
from django.urls import path
from App_RegLog import views

app_name = 'App_RegLog'


urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('user_profile/',views.user_profile, name='user_profile'),
    path('other_user_profile/<username>/', views.other_user_profile, name='other_user_profile'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
    path('post/<pk>/', views.post, name='post')


]

Social_Media/urls.py
    
from django.contrib import admin
from django.urls import path, include

from App_Posts import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_RegLog.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_RegLog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    description = models.TextField(blank=True)
    dob = models.DateField(blank=True, null=True)
    websile = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    def __str__(self):
        return self.user

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    Created_date = models.DateTimeField(auto_now_add=True)

App_RegLog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm #UserCreationForm-> username', 'password1', 'password2',| AuthenticationForm-> username, password
from django.contrib.auth.models import User # 'username', 'password', 'email', 'first_name', 'last_name'

from App_RegLog.models import UserProfile
#UserCreationForm-> sign up form, AuthenticationForm-> log in form

class SignUpForm(UserCreationForm):

    email = forms.EmailField(required=True, label="", widget=forms.EmailInput(attrs={'placeholder':'Email'}))
    username =forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class LogInForm(AuthenticationForm):
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')



class UserProfileEditForm(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user', )

App_RegLog/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from App_RegLog.forms import SignUpForm, LogInForm, UserProfileEditForm
from App_Posts.forms import PostsForm

from django.contrib.auth.models import User

from App_RegLog.models import UserProfile, Follow
from App_Posts.models import Post



# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registration=False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            registration=True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_RegLog:log_in'))
    return render(request, 'App_RegLog/sign_up.html', context={'form':form})




def log_in(request):
    form = LogInForm()
    if request.method == 'POST':
        form = LogInForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Posts:home'))
    return render(request, 'App_RegLog/log_in.html', context={'form':form})



@login_required
def profile_edit(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = UserProfileEditForm(instance=current_user)
    if request.method == 'POST':
        form = UserProfileEditForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = UserProfileEditForm(instance=request.user)
            return HttpResponseRedirect(reverse('App_RegLog:user_profile'))
    return render(request, 'App_RegLog/profile_edit.html', context={'form':form})



@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_RegLog:log_in'))

@login_required
def user_profile(request):
    form = PostsForm()
    if request.method == 'POST':
        form = PostsForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('App_RegLog:user_profile'))
    return render(request, 'App_RegLog/user_profile.html', context={'form':form})



@login_required
def other_user_profile(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_RegLog:user_profile'))
    return render(request, 'App_RegLog/other_user_profile.html', context={'user_other':user_other, 'already_followed':already_followed})



@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following = following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following = following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_RegLog:other_user_profile', kwargs={'username':username}))


@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_RegLog:other_user_profile', kwargs={'username':username}))

def post(request, pk):
    post = Post.objects.get(id=pk)
    return render(request, 'App_RegLog/image_show.html', context={'post':post})

templates/App_RegLog/image_show.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} Image{% endblock %}

{% block link_css %}
<link rel="stylesheet" href="{% static 'css/.css' %}">
{% endblock %}





{% block body %}
<h4>{{post.caption}}</h4>
<br><br>
<img src="/media/{{post.image}}" title={{post.caption}} width="680px">

{% endblock %}

templates/App_RegLog/log_in.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %}LOG IN{% endblock %}


{% block link_css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}




{% block body %}
<center>
  <div class="log_in">
    <h3>Log In</h3>
    <hr>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit"  value="Log In" class="btn btn-success btn-lg btn-block">
    </form>
  </div>
  <br>
  <div class="sign_up">
    <p>Don't have an account? <a href="{% url 'App_RegLog:sign_up' %}">Sign up</a></p>
  </div>
</center>
{% endblock %}

templates/App_RegLog/other_user_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title_block %} {{user_other.user_profile.full_name}} (@{{user_other.username}}){% endblock %}


{% block link_css %}
<link rel="stylesheet" href="{% static 'css/userprofileposts.css' %}">
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-sm-4">
    {% if user_other.user_profile.profile_pic %}
    <img src="/media/{{user_other.user_profile.profile_pic}}" width="250px" height="230px" class="rounded-circle">
    {% else %}
    <img src="/media/profile_pics/default.png" width="250px%" height="230px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-8">
    {% if not already_followed %}
    <h3>{{ user_other.user_profile.full_name}} &nbsp; <a href="{% url 'App_RegLog:follow' username=user_other.username %}"class="btn btn-primary">Follow</a></h3>
    {% else %}
    <h3>{{ user_other.user_profile.full_name}} &nbsp; <a href="{% url 'App_RegLog:unfollow' username=user_other.username %}"class="btn btn-primary">Unollow</a></h3>
    {% endif %}
    <br>
    <p>@{{ user_other.username}}</p>
    <br>
    <h5>{{user_other.user_post.count }} Posts &nbsp; &nbsp; {{user_other.following.count }} Follower &nbsp; &nbsp; {{user_other.follower.count}} Following</h5>
    <br>
    <p>{{user_other.user_profile.description|linebreaks}}</p>
    <!-- <h4></h4> -->
  </div>
</div>
<hr>


<br>


  {% for post in user_other.user_post.all %}
  <div class="gallary">
    <div class="padding">
      <img src="/media/{{post.image}}" title={{post.caption}} height="400px" width="600px">
    </div>
  </div>
  {% endfor %}
{% endblock %}

templates/App_RegLog/profile_edit.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} PROFILE | EDIT PROFILE {% endblock %}



{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <button type="submit" name="button" class="btn btn-primary">Save</button>

</form>
{% endblock %}

templates/App_RegLog/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} SIGN UP{% endblock %}



{% block link_css %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}



{% block body %}
<center>
<div class="sign_up">
  <h3>Sign Up</h3>
  <hr>
  <form method="POST">
    {{ form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg btn-block">Sign Up</button>
  </form>
</div>
<br>
<div class="log_in">
  <p>Have an account? <a href="{% url 'App_RegLog:log_in' %}">Log In</a></p>
</div>
</center>
{% endblock %}

templates/App_RegLog/user_profile.html
{% extends 'navbar.html' %}


{% load crispy_forms_tags %}
{% load static %}

{% block title_block %} {{user.user_profile.full_name}} (@{{user.username}}){% endblock %}


{% block link_css %}
<link rel="stylesheet" href="{% static 'css/userprofileposts.css' %}">
{% endblock %}




{% block body %}

<div class="row">
  <div class="col-sm-4">
    {% if user.user_profile.profile_pic %}
    <img src="/media/{{user.user_profile.profile_pic}}" width="250px" height="230px" class="rounded-circle">
    {% else %}
    <img src="/media/profile_pics/default.png" width="250px%" height="230px" class="rounded-circle">
    {% endif %}
  </div>
  <div class="col-sm-4">
    <h3>{{ user.user_profile.full_name}}&nbsp; <a href="{% url 'App_RegLog:profile_edit' %}"class="btn btn-light">Edit Profile</a></h3>
    <br>
    <p>@{{ user.username}}</p>
    <br>
    <h5>{{user.user_post.count }} Posts &nbsp; &nbsp; {{user.following.count }} Follower &nbsp; &nbsp; {{user.follower.count}} Following</h5>
    <br>
    <p>{{user.user_profile.description|linebreaks}}</p>
    <!-- <h4></h4> -->
  </div>
</div>

<hr>

<br>
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create New Post</button>
<br>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Create Post</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                  {{ form|crispy}}
                  {% csrf_token %}
                  <button type="submit" name="button" class="btn btn-success">Post</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<br>


  {% for post in user.user_post.all %}
  <div class="gallary">
    <div class="padding">
      <a href="{% url 'App_RegLog:post' post.id %}"><img src="/media/{{post.image}}" title={{post.caption}} height="400px" width="600px"></a>

    </div>
  </div>
  {% endfor %}

<br><br><br>












{% endblock %}