App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'


urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike'),





]

App_RegLog/urls.py
from django.urls import path
from App_RegLog import views

app_name = 'App_RegLog'


urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('user_profile/',views.user_profile, name='user_profile'),
    path('other_user_profile/<username>/', views.other_user_profile, name='other_user_profile'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
    path('post/<pk>/', views.post, name='post')


]

Social_Media/urls.py
    
from django.contrib import admin
from django.urls import path, include

from App_Posts import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_RegLog.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


  <!-- font-awesome library -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- <title>{{ title }}</title> -->
  <title>{% block title_block %}  {% endblock %}</title>

  {% load static %}
  {% block link_css %} {% endblock %}






</head>
<body>

  <div class="container" style="padding-top:40px;">
    {% block body %}

    {% endblock %}
  </div>

</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


  <!-- font-awesome library -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- <title>{{ title }}</title> -->
  <title>{% block title_block %}  {% endblock %}</title>

  {% load static %}
  {% block link_css %} {% endblock %}






</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><b>Instagram</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'App_Posts:home' %}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">Notifications</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Massages</a>
              </li>
              &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
              <form class="form-inline my-2 my-lg-0" method="GET">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>


          </ul>
          <ul class="navbar-nav my-2 my-lg-0">
              <li class="nav-item ">
                  <a class="nav-link btn btn-light" href="{% url 'App_RegLog:logout_user' %}">Log Out</a>
              </li>
              <li class="nav-item ">
                  {% if user.user_profile.profile_pic %}
                  <a class="nav-link" href="{% url 'App_RegLog:user_profile' %}"><img
                          src="/media/{{user.user_profile.profile_pic}}" width="35px" class="rounded-circle"></a>
                  {% else %}
                  <a class="nav-link" href="{% url 'App_RegLog:user_profile' %}"><img src="/media/profile_pics/default.png" width="35px" class="rounded-circle"></a>
                  {% endif %}
              </li>
          </ul>
      </div>
  </nav>



  <div class="container" style="padding-top:40px;">
    {% block body %}

    {% endblock %}
  </div>

</body>
</html>