App_Posts/urls.py
from django.urls import path
from App_Posts import views

app_name = 'App_Posts'


urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike'),





]

App_RegLog/urls.py
from django.urls import path
from App_RegLog import views

app_name = 'App_RegLog'


urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_in/', views.log_in, name='log_in'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('user_profile/',views.user_profile, name='user_profile'),
    path('other_user_profile/<username>/', views.other_user_profile, name='other_user_profile'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow'),
    path('post/<pk>/', views.post, name='post')


]

Social_Media/urls.py
    
from django.contrib import admin
from django.urls import path, include

from App_Posts import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_RegLog.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post')
    image = models.ImageField(upload_to='post_images', blank=True)
    caption = models.CharField(max_length=264, blank=True)
    upload_data = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-update_date',]

    def __str__(self):
        return self.image


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

App_Posts/forms.py
from django import forms
from App_Posts.models import Post

class PostsForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image', 'caption')

App_Posts/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from App_RegLog.models import UserProfile, Follow
from App_Posts.models import Post, Like

from django.contrib.auth.models import User


# Create your views here.
@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(author__in=following_list.values_list('following'))

    #like er kaj ekhane o achy
    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)


    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)

    return render(request, 'App_Posts/home.html', context={'search':search, 'result':result, 'posts':posts, 'liked_post_list':liked_post_list })


@login_required
def like(request, pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(user=user, post=post)
    if not already_liked:
        liked_post = Like(post=post, user=user)
        liked_post.save()

    return HttpResponseRedirect(reverse('App_Posts:home'))


@login_required
def unlike(request, pk):
    post = Post.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(user=user, post=post)
    already_liked.delete()

    return HttpResponseRedirect(reverse('App_Posts:home'))

templates/App_Posts/home.html
{% extends 'navbar.html' %}




{% block title_block %}HOME{% endblock %}




{% block body %}

  {% if search %}

    {% for user in result %}
    <div class="row">
      <div class="col-sm-1">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" width="35px" class="rounded-circle">
        {% else %}
        <img src="/media/profile_pics/default.png" width="35px" class="rounded-circle">
        {% endif %}
      </div>
      <div class="col-sm-11">
        <a href="{% url 'App_RegLog:other_user_profile' username=user.username %}"><b>{{ user.user_profile.full_name }}</b> @{{ user.username }}</a>
      </div>
    </div>
    <br>
    {% endfor %}

  {% else %}

  <div class="row">
    <div class="col-sm-8">

        {% for post in posts %}
        <div style="border: 2px solid #888888; ">
          <div style="padding: 10px;">
            {% if post.author.user_profile.profile_pic %}
              <img src="/media/{{post.author.user_profile.profile_pic}}" width="35px" class="rounded-circle">
            {% else %}
              <img src="/media/profile_pics/default.png" width="35px" class="rounded-circle">
            {% endif %}

            <a href="{% url 'App_RegLog:other_user_profile' username=post.author %}"><b>{{ post.author.user_profile.full_name }} </b>&nbsp; @{{post.author}}</a>
          </div>
          <img src="/media/{{post.image}}" width="100%">
          <div style="padding:20px">


            {% if post.pk in liked_post_list %}
            <a href="{% url 'App_Posts:unlike' pk=post.pk %}"><i class="fa fa-heart" style="font-size:30px"></i></a>

            {% else %}
            <a href="{% url 'App_Posts:like' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size:30px"></i></a>
            {% endif %}
            <br>
            {{post.liked_post.count}} Likes
            <br>
            <a href="{% url 'App_RegLog:other_user_profile' username=post.author %}">{{post.author}}</a>
            {{post.caption}}

          </div>
        </div>
        <br><br>
        {% endfor %}

    </div>
    <div class="col-sm-4">
      <div class="row">
        <div class="col-sm-2">
          {% if user.user_profile.profile_pic %}
          <img src="/media/{{user.user_profile.profile_pic}}" width="35px" class="rounded-circle">
          {% else %}
          <img src="/media/profile_pics/default.png" width="35px" class="rounded-circle">
          {% endif %}
        </div>
        <div class="col-sm-10">
          <b>{{user.user_profile.full_name}}</b>
          <br>
          {{user.username}}
        </div>
      </div>
    </div>
  </div>
  {% endif %}

{% endblock %}